name = "BECA Theme"
license = "MIT"
licenselink = "https://github.com/yourname/beca-theme/blob/master/LICENSE"
description = "A minimalist theme for writers and storytellers"
homepage = "https://github.com/yourname/beca-theme"
tags = ["blog", "minimal", "clean", "responsive", "writing"]
features = ["responsive", "blog"]
min_version = "0.92.0"

[author]
  name = "BECA Theme Author"
  homepage = "https://github.com/yourname"

